### ISSUE TITLE
No autorization for Discover method

### ISSUE THREAD

**Issue by ViValentin** [chris1642/Power-BI-Backup-Impact-Analysis-Governance-Solution#1]
Hello,
When running the cript I have an error with Tabular Editor 2.25 saying that I have no autorization to call Discover method. It induce taht all BIM files are not downloaded and linked analytic is missing :-(

**Comment by chris1642** [comment]
This should be ok and is expected if it's not a premium workspace or you don't have permissions within the workspace. 

The later steps handle this by downloading the model via a PBIX report and extracting the BIM using PBI-tools within the config folder. 

At the very end, do you see a bim file in the Model Backups folder or within the Power BI governance model, is the model an option to explore?

**Comment by ViValentin** [comment]
C:\Power BI Backups\Model Backups\<Date> folders are all umpty :-(
Perhaps linked to line 548
547           Write-Output "Generating .bim for $cleanWorkspaceName ~ $cleanReportName using $driveLetter"
548            pbi-tools generate-bim $driveLetter -transforms RemovePBIDataSourceVersion

Is $DriveLetter the correct variable as there is no reference to the Bim file we want to generate within pbi-tools command line?

**Comment by chris1642** [comment]
Yes - When using PBI-Tools alongside the 'Workspace Name ~ Report Name.pbix' format, when the report is extracted to a folder structure, it sometimes will go beyond the 255 character limit within Windows.

The script helps get around this by creating a temporary Q drive and extracting the pbix files to the base Q:\ instead of C:\Power BI Backups\Report Backups Backups\Date\Report Name

**Comment by chris1642** [comment]
Great to hear!

For clarity, 'Download Reports' and 'Export to Excel' are enabled in organizations by default within the tenant admin settings. (I recently set up a new tenant to understand what is enabled by default and help ensure this works for the majority of people)

However, only 'Download Reports' is required to be enabled. 'Export to Excel' can be disabled and the script run without issues. I just tested this.

**Comment by chris1642** [comment]
Closed and resolved!

1. Discover Method errors are due to not being a Premium, Fabric, or PPU Workspace. This is not an issue because the script handles Pro workspaces later in the script. 
2. 'Download Reports' should be enabled within the Tenant settings. This is enabled by default within the Tenant - and if disabled, no user can download reports or models from the Power BI (i.e. it would be rare to have this disabled since it means no one in the org can download PBIX files, even developers).

**Comment by chris1642** [comment]
Closed and resolved!

1. Discover Method errors are due to not being a Premium, Fabric, or PPU Workspace. This is not an issue because the script handles Pro workspaces later in the script. 

2. 'Download Reports' should be enabled within the Tenant settings. This is enabled by default within the Tenant - and if disabled, no user can download reports or models from Power BI (i.e. it would be rare to have this disabled since it means no one in the org can download reports from workspaces, even developers).
